### ISSUE TITLE
Text styles are not used in resume

### ISSUE THREAD

**Issue by jonathandefraiteur** [sellsecure/alfredbot-slack#1]
Exemple :
> Hotfix du bug DQE/Yahoo. _Proposition_ d'un *fix* API/Core (ajout d'une logique de suggestion d'existence au lieu d'un `set`). Continuer Arkowl.

**Comment by theBlueBisu** [comment]
Done with [PR #4](https://github.com/sellsecure/alfredbot-slack/pull/4)

**Comment by theBlueBisu** [comment]
Done with PR #4

**Comment by jonathandefraiteur** [comment]
Done with PR #4
